repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: detect-private-key

  - repo: local
    hooks:
      - id: ruff_format
        name: Format with ruff
        language: system
        types: [python]
        entry: ruff format

      - id: ruff_lint
        name: Lint with ruff
        language: system
        types: [python]
        entry: ruff check
        args: ["--fix"]
